import re
from typing import Callable

def generator_numbers(text: str):
    """
    Generate numbers found in the input text.
    
    :param text: Input string containing numbers.
    """

    #Regex pattern explanation:
    #(?<=\s) - Positive lookbehind for a whitespace character
    #\d+ - One or more digits
    #(?:\.\d+)? - Non-capturing group for optional decimal part
    #(?=\s) - Positive lookahead for a whitespace character

    pattern = r"(?<=\s)\d+(?:\.\d+)?(?=\s)"
    
    for match in re.finditer(pattern, text):
        yield float(match.group())

def sum_profit(text: str, func: Callable) -> float:
    """
    Calculate the sum of numbers generated by the provided function.
    
    :param text: Input string containing numbers.
    :param func: Function that generates numbers from the input text.
    :return: Sum of the generated numbers.
    """
    return sum(func(text))
